### ISSUE TITLE
Staff Directory - Subject filtering not showing all tagged staff

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#105]
## Expected behavior
All staff with assigned subject X displays in Staff Directory when filter down to subject X.

## Actual behavior
Social Sciences seems to have a bug where the newest staff member, Cecilia, does not display in the [filtered Social Sciences view](https://www.lib.uchicago.edu/about/directory/?view=staff&subject=Social%20Sciences). Her staff page has "Social Sciences" as her one and only subject.

**Comment by johnjung** [comment]
The expected behavior was actually occurring. Cecilia's department is social sciences, which is why the words "social sciences" appeared on her staff page. Social sciences was not selected as a subject on her staff page. I added that subject to her staff page and now she appears in the directory view.
