### ISSUE TITLE
Wagtail Map Pages Linked to Catalog Map Links

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#114]
Since the floor maps have been merged to include both the bookstacks and reading rooms, some of the Reg floor map pages will be unpublished.

## Priority: B Level
The most problematic will be B Level's link to OLE.
- There are currently two links for B Level, [B Level West](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/b-level-west/) and [B Level East](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/b-level-east/).
- These will now be one page; these links will need to be resolved in the Catalog.
- The new link will likely be https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/b-level

## Verification: Floors 2-5
We need to verify that the following pages that are slated to be unpublished are not being linked elsewhere.
- [Regenstein 5th Floor Reading Room](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/5th-floor-reading-room/)
- [Regenstein 4th Floor Reading Room](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/4th-floor-reading-room/)
- [Regenstein 3rd Floor Reading Room](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/3rd-floor-reading-room/)
- [Regenstein 2nd Floor Reading Room](https://www.lib.uchicago.edu/spaces/joseph-regenstein-library/2nd-floor-reading-room/)

**Comment by kzadrozny** [comment]
David Bottorff has also pointed out how these pages link to Spaces pages, so we will need to update space pages that link to bookstacks floorplans to link to new main floorplans.

**Comment by dbottorff** [comment]
Just noting that we should probably unpublish the bookstacks floor pages rather than the reading room pages, as there are fewer space pages to relink. The URL of the reading room pages will change regardless, however, so the catalog map lookup will need to take that into account.

If possible, the Map lookup text should remain the same, in that, depending on the location in Vufind, the text should remain either "3rd Floor Bookstacks Map" or "3rd Floor Reading Room Map" even though both will link to the same floor map page.

**Comment by dbottorff** [comment]
I've tested by removing the floor page association from the Mansueto pages (since they won't have a floor page initially), and the space browse, simply grays out the option of selecting a floor. See:

[https://www.lib.uchicago.edu/spaces/?building=The%20Joe%20and%20Rika%20Mansueto%20Library&space_type=is_study_space](url)

I also briefly changed the title of the B Level East floor page to include the text TEST, and this was immediately reflected in the space browse dropdown. So it looks like any changes we make to these pages will be automatically reflected in the space browse, without further intervention on our part.

**Comment by dbottorff** [comment]
B Level West is also the floor page that should be retained and updated, as it has multiple special use space pages associated with it, as opposed to B Level East, which has only the Bookstacks space page

**Comment by kzadrozny** [comment]
After the DLDC crew meeting, we have created this checklist for update:

- [ ] Review how Locations are assigned to specific floor maps for Reg
- [ ] Upload new floor maps in Reading Rooms and B Level West
        (Keep Bookstacks and B Level East as is as a backup while changes take place)
- [ ] Update slugs for Reading Rooms and B Level West to remove "reading room" or "west"
- [ ] Update map links in the Catalog
- [ ] Update the Reg "About" page where all floor map links are listed
- [ ] Verify Space Browse is working with new data
- [ ] Do a find and replace on LibGuides for the old URLs
- [ ] Unpublish Bookstacks and B Level East pages once all changes have been implemented and verified
- [ ] Make Loop News post about the change and recommend staff review their links

**Comment by kzadrozny** [comment]
URLs to be edited, unplublished, and updates are listed in [this spreadsheet](https://docs.google.com/spreadsheets/d/1bxjb6AaPUt2DjWIJtNNRiElvd82gxia-TqFwjb4Y-OQ/edit?usp=sharing) (Only Maps team can view)

**Comment by bbusenius** [comment]
I've created and updated a copy of the maplookup.xml with the new links:

/projects/forms2/lib/maplookup/maplookup-NEW-MAPS-PRELAUNCH.xml

All we should need to do is rename it to maplookup.xml when it's time to launch. This will cross off "Update map links in the Catalog".

**Comment by kzadrozny** [comment]
All the tasks have been completed and there have been no reported issues with the launch.
