### ISSUE TITLE
Cannot create Collection or Exhibit pages

### ISSUE THREAD

**Issue by dbietila** [uchicago-library/library_website#273]
Collection and Exhibit page types cannot be created in Wagtail, even in appropriate locations (the Collections and Exhibits directories, respectively). This problem exists both on production and test instances of Wagtail.

Ideally, they should be creatable only in these locations.

**Comment by bbusenius** [comment]
This is fixed in dev and will be deployed shortly. I take responsibility for this problem. I definitely should have caught this when I was doing the code review.

We will not be able to limit the creation of these page types to these locations because we are using `StandardPages` to store collection and exhibit pages. In order to limit them, we would need to create 2 additional container page types and allow them under `StandardPages`. Then we could set the limit on the container page types and remove the current ones under `StandardPages`.

This would still leave us with two extra page types and we'd have to move all of the collection and exhibit pages. I cannot recommend this.

**Comment by kzadrozny** [comment]
I have tested production and am able to make Collection pages without issue. I consider this issue resolved with the possibility of revisiting better solutions in the future.
