### ISSUE TITLE
CGIMail error in Loop

### ISSUE THREAD

**Issue by kzadrozny** [uchicago-library/library_website#541]
CGIMail not working in Loop due to a security feature blocking the HTTP_REFERER. Sysadmins have installed CGI into Loop, so now lib and loop both have their own instances. The Loop json models need to be changed to reflect this local installation.

• Temp fix: change `action="https://lib.uchicago.edu/cgi-bin/cgimail"` to `action="https://loop.lib.uchicago.edu/cgi-bin/cgimail"`
• Long term fix: Ideally both the lib and loop json versions should be `action="/cgi-bin/cgimail"`

**Comment by bbusenius** [comment]
This is easily achievable with a config change. The current config looks like this:

```
CGI_MAIL_SERVICE = 'https://www.lib.uchicago.edu/cgi-bin/cgimail/cgimail'
```

Note, the current path in production is `/cgi-bin/cgimail/cgimail'` not `/cgi-bin/cgimail'`. I assume we want the first one, since we don't want to disturb things on production. Anyhow, when I try either of those paths on loop right now, I get a `404 Not Found`. If I set the config to `/cgi-bin/cgimail/cgimail'` it works on production but not on loop. CGIMail Forms use `POST` if that's relevant. Anyhow, it seems like we need a couple of things to proceed:

1. It should be installed on `liblet` and `looplet` so we can test there as well.
2. There must be a tweak needed for loop to work since it's still giving `404`.

Tagging @wekinglypigs to see if she can assist.

**Comment by bbusenius** [comment]
Ah, nevermind number 2. It looks like I was testing in the looplet browser tab. :man_facepalming:
